name: 'Ollama Code Review'
description: 'Request a code review from the Ollama server for a GitHub pull request.'
inputs:
    OLLAMA_API_URL:
        description: 'The URL of the Ollama API server.'
        required: true
        default: 'http://localhost:11434'
    MY_GITHUB_TOKEN:
        description: 'The GitHub token to use for making API requests.'
        required: true
    OWNER:
        description: 'The owner of the repository.'
        required: true
    REPO:
        description: 'The name of the repository.'
        required: true
    PR_NUMBER:
        description: 'The number of the pull request.'
        required: true
    MY_GITHUB_API_URL:
        description: 'The GitHub url to use for making API requests.'
        required: false
        default: 'https://api.github.com'
    CUSTOM_PROMPT:
        description: 'The custom prompt to use for the review.'
        required: false
        default: ''
    RESPONSE_LANGUAGE:
        description: 'The language to use for the response.'
        required: false
        default: 'English'
    MODEL:
        description: 'The model to use for the review.'
        required: false
        default: 'deepseek-r1:8b'
    TRANSLATION_MODEL:
        description: 'The model to use for translation.'
        required: false
        default: 'exaone3.5:7.8b'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-python@v6
      with:
        python-version: '>=3.6'
    - run: pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash
    - run: python ${{ github.action_path }}/src/ollama_review.py
      shell: bash
      env:
        OLLAMA_API_URL: ${{ inputs.OLLAMA_API_URL }}
        MY_GITHUB_TOKEN: ${{ inputs.MY_GITHUB_TOKEN }}
        OWNER: ${{ inputs.OWNER }}
        REPO: ${{ inputs.REPO }}
        PR_NUMBER: ${{ inputs.PR_NUMBER }}
        MY_GITHUB_API_URL: ${{ inputs.MY_GITHUB_API_URL }}
        CUSTOM_PROMPT: ${{ inputs.CUSTOM_PROMPT }}
        RESPONSE_LANGUAGE: ${{ inputs.RESPONSE_LANGUAGE }}
        MODEL: ${{ inputs.model }}
        TRANSLATION_MODEL: ${{ inputs.TRANSLATION_MODEL }}
branding:
  icon: 'check'
  color: 'blue'
